name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/checkout@v1
      name: Cloning repo
    - name: Setup environment
      run: |
        touch .env
        echo 'REACT_APP_TELEGRAM_API_ID=${{ secrets.REACT_APP_TELEGRAM_API_ID }}' >> .env
        echo 'REACT_APP_TELEGRAM_API_HASH=${{ secrets.REACT_APP_TELEGRAM_API_HASH }}' >> .env
        git config user.email ${{ secrets.COMMITER_EMAIL }}
        git config user.name ${{ secrets.COMMITER_NAME }}
    - name: Installing dependencies
      run: npm ci
    - name: Copying TDWeb files
      run: |
        rm node_modules/tdweb/dist/*
        cp public/*.worker.js node_modules/tdweb/dist/
        cp public/*.wasm node_modules/tdweb/dist/
        cp public/*.mem node_modules/tdweb/dist/
        cp public/tdweb.js node_modules/tdweb/dist/
    - name: Deploying
      run: npm run deploy
      env:
        CI: ""
        CI_REPO: -r https://${{ secrets.PUSH_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
